# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Conan C/C++ Package Manager
email: info@conan.io
description: > # this means to ignore newlines until "baseurl:"
   Full Open Source, MIT, C/C++ Package Manager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.conan.io" # the base hostname & protocol for your site
twitter_username: conan_io
github_username:  conan-io

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from