# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

plugins: [jekyll-paginate]

# Site settings
title: Conan C/C++ Package Manager Blog
email: info@conan.io
description: Blog for the team behind the Fully Open Source, MIT licensed, C/C++ Package Manager.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.conan.io" # the base hostname & protocol for your site
twitter_username: conan_io
github_username:  conan-io
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
